/**
 * Generated by orval v6.6.3 🍺
 * Do not edit manually.
 * angular-typescript-starter
 * BE
 * OpenAPI spec version: 1.0.0
 */
import type { NullableString } from './nullableString';
import type { AuthType } from './authType';

export interface AuthRequest {
  username?: NullableString;
  password?: NullableString;
  authType: AuthType;
  signature?: NullableString;
  publicKey?: NullableString;
}
