/**
 * Generated by orval v6.6.3 🍺
 * Do not edit manually.
 * angular-typescript-starter
 * BE
 * OpenAPI spec version: 1.0.0
 */

export type AuthType = 'STANDARD' | 'W3_WALLET';


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthType = {
  STANDARD: 'STANDARD' as AuthType,
  W3_WALLET: 'W3_WALLET' as AuthType,
};
