/**
 * Generated by orval v6.6.3 🍺
 * Do not edit manually.
 * angular-typescript-starter
 * BE
 * OpenAPI spec version: 1.0.0
 */

export type GetUserByUserTypeParams = { username?: string; email?: string; firstName?: string; lastName?: string; pageNumber?: number; pageSize?: number; filter?: string; sortOrder?: string };
