/**
 * Generated by orval v6.6.3 🍺
 * Do not edit manually.
 * angular-typescript-starter
 * BE
 * OpenAPI spec version: 1.0.0
 */
import { UserType } from './userType';

export type NullableUSERTYPE = UserType | null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NullableUSERTYPE = UserType;
