/**
 * Generated by orval v6.6.3 🍺
 * Do not edit manually.
 * angular-typescript-starter
 * BE
 * OpenAPI spec version: 1.0.0
 */
import type { ISafeUser } from './iSafeUser';

export interface UserPayload {
  user?: ISafeUser;
  users?: ISafeUser[];
  userLength?: number;
  token?: string;
  nonce?: string;
}
