/**
 * Generated by orval v6.6.3 🍺
 * Do not edit manually.
 * angular-typescript-starter
 * BE
 * OpenAPI spec version: 1.0.0
 */
import type { IUser } from './iUser';

export interface AuthPayload {
  user?: IUser;
  token?: string;
}
