/**
 * Generated by orval v6.6.3 🍺
 * Do not edit manually.
 * angular-typescript-starter
 * BE
 * OpenAPI spec version: 1.0.0
 */
import type { PickIUserFirstnameOrLastnameOrUsernameOrEmailOrUserTypeOrCreatedAtOrUpdatedAt } from './pickIUserFirstnameOrLastnameOrUsernameOrEmailOrUserTypeOrCreatedAtOrUpdatedAt';

export type ISafeUser = PickIUserFirstnameOrLastnameOrUsernameOrEmailOrUserTypeOrCreatedAtOrUpdatedAt;
