/**
 * Generated by orval v6.6.3 🍺
 * Do not edit manually.
 * angular-typescript-starter
 * BE
 * OpenAPI spec version: 1.0.0
 */
import type { UserType } from './userType';

/**
 * From T, pick a set of properties whose keys are in the union K
 */
export interface PickIUserFirstnameOrLastnameOrUsernameOrEmailOrUserTypeOrCreatedAtOrUpdatedAt {
  firstname: string;
  lastname: string;
  username: string;
  email: string;
  user_type: UserType;
  createdAt?: string;
  updatedAt?: string;
}
