/**
 * Generated by orval v6.6.3 🍺
 * Do not edit manually.
 * angular-typescript-starter
 * BE
 * OpenAPI spec version: 1.0.0
 */

export type UserType = 'ADMIN' | 'STAFF' | 'USER';


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserType = {
  ADMIN: 'ADMIN' as UserType,
  STAFF: 'STAFF' as UserType,
  USER: 'USER' as UserType,
};
