/**
 * Generated by orval v6.6.3 🍺
 * Do not edit manually.
 * angular-typescript-starter
 * BE
 * OpenAPI spec version: 1.0.0
 */
import type { UserPayload } from './userPayload';

export interface UserResponse {
  success: boolean;
  payload?: UserPayload;
  message?: unknown;
}
