export enum actionTypes {
    SIGNIN = 'SIGNIN',
    AUTHENTICATED = 'AUTHENTICATED',
    SIGNOUT = 'SIGNOUT',
    SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS',
    SHOW_AUTH_MESSAGE = 'SHOW_AUTH_MESSAGE',
    HIDE_AUTH_MESSAGE = 'HIDE_AUTH_MESSAGE',
    SIGNUP = 'SIGNUP',
    SIGNUP_SUCCESS = 'SIGNUP_SUCCESS',
    SHOW_LOADING = 'SHOW_LOADING',
}

